---
- hosts: all
  gather_facts: false
  connection: local

  vars:
    provider_id: "{{ provider_id }}"
    max_retries: 9
    retry_interval: 20

  tasks:
    - debug: var=manageiq.api_url
    - debug: var=manageiq.api_token
    - debug: var=manageiq.service

    - name: Set the Provider URL
      set_fact:
        provider_url: "{{ manageiq.api_url }}/api/providers/{{ provider_id }}"

    - name: Set the Service URL
      set_fact:
        svc_url: "/api/{{ manageiq.service }}"

    - debug: var=svc_url

    # Basic provisioning example for ec2
    - name: Create the instance
      ec2:
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"       #e.g. t2.micro
        image: "{{ image }}"                       #e.g. ami-123456
        wait: "{{ wait }}"                         #e.g. yes or no
        group: "{{ group }}"                       #e.g. webserver
        count: "{{ count }}"                       #e.g. 3
        vpc_subnet_id: "{{ vpc_subnet_id }"        #e.g. subnet-29e63245
        assign_public_ip: "{{ assign_public_ip }}" #e.g. yes or no
